### ISSUE TITLE
problem with new SynapsePay (client init)

### ISSUE THREAD

**Issue by redcap3000** [parlaywithme/meteor-synapsepay#1]
Am receiving this error when attempting to initiate synapse pay within meteor.

`Exception while invoking method 'buy' TypeError: Cannot read property 'clientAddress' of undefined
I20160316-12:26:09.599(-8)?     at new SynapsePay (packages/parlay_synapsepay/server/synapsepay.coffee:46:42)`

Any help?
Have tried

```
this.sp = new SynapsePay({
      development_mode: this.development_mode,
      ip_address: ip,
      client_id : user_id,
      fingerprint: decryptedFingerprint
    });
```

and

```
 this.sp = new SynapsePay({
      development_mode: this.development_mode,
      ip_address: ip,
      fingerprint: decryptedFingerprint
    }, user_id);
```

Same result.

**Comment by lorensr** [comment]
Sorry about that, README is a bit out of date – will update it now

**Comment by lorensr** [comment]
Try this function:

https://github.com/parlaywithme/meteor-synapsepay#getclient

The full diff:

https://github.com/parlaywithme/meteor-synapsepay/compare/ed37f650b02dd811f10f5ae553f2dcc43b771045...master

**Comment by redcap3000** [comment]
The wording is a bit confusing to understand what the value of 'method' needs to be; and wether this is needed (or if it exists) when its not running in the direct scope of a meteor method (as the documentation suggests it should be.) The flow in place had functioned previously (running on serverside code, not within a meteor.method) so I'm confused as to what to change as far as the initialization method.

**Comment by lorensr** [comment]
Got it. Is this better?

https://github.com/parlaywithme/meteor-synapsepay#getclient

**Comment by redcap3000** [comment]
Yes that worked. Thank you.
